"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['font.ttf', 
'background.ogg', 
'background.png', 
'bullet.png', 
'gun.png', 
'pow0.wav', 
'player.png', 
'pow1.wav', 
'rumble.ogg', 
'shield.png', 
'shoot.wav', 
'expl0.wav', 
'expl1.wav', 
'rock.png', 
]

for i in range(9):
    DATA_FILES.append(f'expl{i}.png')
    DATA_FILES.append(f'player_expl{i}.png')

for i in range(7):
    DATA_FILES.append(f'rock{i}.png')


OPTIONS = {
    'iconfile':'player.png'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
